os:
  - linux
  - osx

language: c++

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y gfortran; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pushd $HOME && mkdir cmake3.1 && cd cmake3.1 && (curl "http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x) && cd cmake-*/bin && export PATH="${PWD}:${PATH}"; popd; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; brew outdated cmake || brew upgrade cmake ; brew install expat ; fi
    - cmake --version

script:
    - git submodule init
    - git submodule update
    - cd ..
    - mkdir _build
    - cd _build
    - travis_wait cmake -DGIT_PROTOCOL=git:// -DCDAT_BUILD_MODE=LEAN -DCDAT_BUILD_GUI=OFF -DCDAT_BUILD_SCIPY=OFF ../uvcdat
    - travis_wait ctest -VV -S ../uvcdat/CMake/travis_build.cmake
    - travis_wait ctest -VV -S ../uvcdat/CMake/travis_submit.cmake
