os:
  - linux
  - osx

language: c++

before_install:
    - if [ "$TRAVIS_OS_NAME"="linux" ]; then sudo apt-get update -qq; sudo add-apt-repository ppa:kubuntu-ppa/beta -y; sudo apt-get update; sudo apt-get install -y cmake; sudo apt-get install -y gfortran; fi

script:
    - git submodule init
    - git submodule update
    - cd ..
    - mkdir _build
    - cd _build
    - cmake ../uvcdat
    - cmake -DCDAT_DISPLAY_LOG:BOOL=ON -DCDAT_BUILD_LEAN:BOOL=ON .
    - make -j4